package top.wkbin.taixu.runtime.privilege

import android.content.Context
import android.content.pm.PackageManager
import android.os.IBinder
import java.lang.reflect.InvocationTargetException
import java.lang.reflect.Method
import java.util.concurrent.ConcurrentHashMap
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.lsposed.hiddenapibypass.HiddenApiBypass
import rikka.shizuku.ShizukuBinderWrapper
import rikka.shizuku.SystemServiceHelper

/** Tri-state Binder direct-call result: channel unavailable (fallback to shell) vs remote failure must be distinguished. */
sealed interface BinderOutcome {
    /** Binder channel unavailable or interface reflection failed; caller should fallback to shell execution. */
    data object ChannelUnavailable : BinderOutcome

    /** Call succeeded; success is remote judgment result. */
    data class Success(val success: Boolean) : BinderOutcome

    /** Channel available but remote failed (SecurityException / RemoteException / IllegalArgumentException). */
    data class Failed(val message: String) : BinderOutcome
}

/**
 * Collection of system service methods called directly via Shizuku Binder:
 * Avoids shell command escaping hell; errors returned in typed fashion.
 *
 * Implementation deliberately chooses REFLECTION over custom AIDL stub subset:
 * AIDL transaction codes generated by "declaration order in interface file"; custom
 * subset vs framework full interface almost certainly misalign, silently calling
 * wrong system method. framework classes like [PackageManager]'s `Stub.asInterface`
 * return proxy with transaction codes guaranteed by framework to match server side —
 * reflect to get that method, zero dependency, zero misalignment.
 *
 * Only meaningful when privilege mode is SHIZUKU; ROOT/PROOT use existing shell path.
 */
class ShizukuSystemApis(
    private val context: Context,
) {
    init {
        // API 28+ hidden API enforcement blocks IPackageManager$Stub / $Stub$Proxy
        // loading and method reflection. AndroidHiddenApiBypass uses ART metadata trick
        // for targeted exemption; only allows needed declaration prefixes, no global exemption.
        // Android <28 has no such restriction; exemption failure safely ignored.
        runCatching { HiddenApiBypass.setHiddenApiExemptions("Landroid/content/pm/IPackageManager") }
    }

    private val proxies = ConcurrentHashMap<String, Any>()

    private val intType: Class<*> = Integer.TYPE
    private val strType: Class<*> = String::class.java

    /**
     * Grant runtime permission, equivalent to shell `pm grant <pkg> <permission>`.
     */
    suspend fun grantRuntimePermission(pkg: String, permission: String, userId: Int): BinderOutcome =
        withContext(Dispatchers.IO) {
            invokeOnPackageService(
                method = "grantRuntimePermission",
                parameterTypes = arrayOf(strType, strType, intType),
                args = arrayOf(pkg, permission, userId),
                interpret = { BinderOutcome.Success(true) },
            )
        }

    /**
     * Set application enabled state, equivalent to shell `pm enable/disable-user`.
     * [enabled] maps to COMPONENT_ENABLED_STATE_ENABLED / DISABLED_USER.
     */
    suspend fun setApplicationEnabledSetting(pkg: String, enabled: Boolean, userId: Int): BinderOutcome =
        withContext(Dispatchers.IO) {
            val newState =
                if (enabled) PackageManager.COMPONENT_ENABLED_STATE_ENABLED
                else PackageManager.COMPONENT_ENABLED_STATE_DISABLED_USER
            invokeOnPackageService(
                method = "setApplicationEnabledSetting",
                parameterTypes = arrayOf(strType, intType, intType, intType, strType),
                args = arrayOf(pkg, newState, 0, userId, context.packageName),
                interpret = { BinderOutcome.Success(true) },
            )
        }

    private fun packageProxy(): Any? {
        // "package" system service binder, wrapped by Shizuku, passes all calls as shell identity.
        proxies["package"]?.let { return it }
        val created = runCatching {
            val wrapper: IBinder = ShizukuBinderWrapper(SystemServiceHelper.getSystemService("package"))
            val stubClass = Class.forName("android.content.pm.IPackageManager\$Stub")
            stubClass.getMethod("asInterface", IBinder::class.java).invoke(null, wrapper)
        }.getOrNull() ?: return null
        proxies["package"] = created
        return created
    }

    private fun invokeOnPackageService(
        method: String,
        parameterTypes: Array<Class<*>>,
        args: Array<Any?>,
        interpret: (Any?) -> BinderOutcome,
    ): BinderOutcome {
        val proxy = packageProxy() ?: return BinderOutcome.ChannelUnavailable
        return try {
            val target: Method = proxy.javaClass.methods.firstOrNull {
                it.name == method && it.parameterTypes.contentEquals(parameterTypes)
            } ?: return BinderOutcome.ChannelUnavailable
            interpret(target.invoke(proxy, *args))
        } catch (invocation: InvocationTargetException) {
            BinderOutcome.Failed(invocation.cause?.message ?: invocation.cause?.toString() ?: "Unknown host error")
        } catch (reflective: ReflectiveOperationException) {
            BinderOutcome.ChannelUnavailable
        }
    }
}
